import {getPlaylistItems} from './utils/youtube.js'
const print = console.log


function isAutoGeneratedPlaylist(plid)
{
	return !/^PL?/.test(plid);
}

let parsed = new URL("https://www.youtube.com/playlist?list=PLV83totEoGzbfBkkKLxZsYbp3NyJrYrZG".trim())
const isYouTube = /^(www\.|m\.|music\.|gaming\.)?(youtube\.com|youtu\.be)$/.test(parsed.hostname);
if(!isYouTube)
{
	throw Error("Not a YouTube domain: ", {
		cause: "Invalid Youtube url: " + parsed.hostname
	});
}
const isYouTubeMusic = /music\.youtube\.com\/?/.test(parsed.hostname);
print({"hostname": parsed.hostname, isYouTube, isYouTubeMusic})
const params = parsed.searchParams;
const isPlaylist = parsed.pathname === '/playlist' && params.has('list');
const isVideo = (parsed.pathname === '/watch' && params.has('v')) || parsed.hostname === 'youtu.be';
print({params, isPlaylist, isVideo})
if(isPlaylist)
{
	let playListId = params.get('list')
	print({isAutoGeneratedPlaylist : isAutoGeneratedPlaylist(playListId), playListId}) // 🔁 Bu otomatik oluşturulmuş bir karışık liste (Mix). Bu tür listeler desteklenmiyor.
	// Youtube api den playlist içeriğini al ve sıraya ekle
	print(await getPlaylistItems(playListId))
}
else if(isVideo)
{
	let id = params.get('v')
	let hasPlaylistId = params.has('list')
	if(hasPlaylistId)
	{
		let index = params.has('index') ? parseInt(params.get('index')) ? parseInt(params.get('index')) - 1 : 0 : 0
		print({index})
		// Youtube api den playlist içeriğini al ve sıraya ekle index den sonrasını
	}
	else
	{
		// şarkıyı direk listeye ekle ve ya oynat.
	}
}
else
	throw new Error("An Error Occurred", {cause: {isVideo, isPlaylist}});