import axios from 'axios';


/**
 * 
 * @param {string} seconds 
 * @returns string
 */
export function formatDuration(seconds) {
	seconds = parseInt(seconds);
	if (isNaN(seconds)) return "Bilinmiyor";

	const hrs = Math.floor(seconds / 3600);
	const mins = Math.floor((seconds % 3600) / 60);
	const secs = seconds % 60;

	const padded = (n) => n.toString().padStart(2, '0');

	if (hrs > 0) {
		return `${hrs}:${padded(mins)}:${padded(secs)}`;
	} else {
		return `${padded(mins)}:${padded(secs)}`;
	}
}

/**
 * 
 * @param {string} str 
 * @returns 
 */
export function isValidUrl(str) {
	try {
		return new URL(str);
	} catch (err) {
		return null;
	}
}

/**
 * 
 * @param {string} plid 
 * @returns boolen
 */
function isAutoGeneratedPlaylist(plid)
{
	return !/^PL?/.test(plid);
}